package aws.lambda.factory.types;
public enum LambdaType {
	SQS,API_GATEWAY,DYNAMO_DB,APPLICATION_LOAD_BALANCER,CLOUD_FRONT,STEP_FUNCTIONS,S3,SNS,EMAIL_SERVICE,CLOUD_FORMATION,
	CODE_PIPELINE,CLOUD_WATCH_LOGS,CLOUD_WATCH_EVENTS
}
